# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parentList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.TodoList')),
            ],
        ),
        migrations.AddField(
            model_name='todotag',
            name='tasks',
            field=models.ManyToManyField(related_name='tags', to='api.TodoTask'),
        ),
    ]
